name: On Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'images/**'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run analysis & Upload results to DynamoDB (Prod)
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          DYNAMODB_TABLE: ${{ secrets.DYNAMODB_PROD }}
        run: |
          python image_analyzer.py
